language: csharp
mono: 5.2.0
solution: "./HacarusVisualInspectionApi/HacarusVisualInspectionApi.sln"
dotnet: 2.1.301
install:
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
script:
  - dotnet build HacarusVisualInspectionApi
  - dotnet restore
  - dotnet test HacarusVisualInspectionApi.Tests
  - if [ -n "$TRAVIS_TAG" ]; then 
    xbuild /p:Configuration=Release ./HacarusVisualInspectionApi/HacarusVisualInspectionApi.sln
    nuget pack ./HacarusVisualInspectionApi/HacarusVisualInspectionApi.nuspec -Verbosity detailed
    nuget push ./SDDApi.*.nupkg -Verbosity detailed -ApiKey $NugetApiKey -Source $Source
    fi
